backend:
  name: git-gateway
  branch: blog # Branch to update (optional; defaults to master)

media_folder: 'src/assets/blog' # Location where files will be stored in the repo
public_folder: 'src/assets/blog' # The src attribute for uploaded media
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    folder: 'src/content/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    fields: # The fields for each document, usually in frontmatter
      - { label: 'Titulo', name: 'title', widget: 'string' }
      - { label: 'Fecha de publicación', name: 'date', widget: 'datetime' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Resumen', name: 'summery', widget:'text' }
      - { label: 'Contenido', name: 'body', widget: 'markdown' }
